wip++ print usage stats gracefully

diff --git a/.github/docker/Dockerfile.linux.base b/.github/docker/Dockerfile.linux.base
--- a/.github/docker/Dockerfile.linux.base
+++ b/.github/docker/Dockerfile.linux.base
@@ -54,6 +54,9 @@ RUN printf '%s\n' \
         > "$MOZ_DIR/mozconfig"
 
 RUN set -a && for f in /etc/environment.d/*.conf; do [ -r "$f" ] && . "$f"; done && set +a && \
-    cd "$MOZ_DIR" && ./mach build && sccache --show-stats
+    cd "$MOZ_DIR" && ./mach build
+
+RUN cd "$MOZ_DIR" && ./mach resource-usage || echo "::warning::mach resource-usage failed; view above output for details"
+RUN sccache --show-stats || echo "::warning::sccache --show-stats failed; view above output for details"
 
 WORKDIR /build
diff --git a/.github/docker/Dockerfile.linux.build b/.github/docker/Dockerfile.linux.build
--- a/.github/docker/Dockerfile.linux.build
+++ b/.github/docker/Dockerfile.linux.build
@@ -15,7 +15,10 @@ RUN set -a && for f in /etc/environment.d/*.conf; do [ -r "$f" ] && . "$f"; done
     cd "$MOZ_DIR/toolkit/components/berytus" && npm run build && \
     cd "$MOZ_DIR/browser/extensions/secretstar" && CI=false npm run build && \
     cd "$MOZ_DIR/browser/extensions/secretstar" && ./moz.build.sh && \
-    cd "$MOZ_DIR" && ./mach build && sccache --show-stats
+    cd "$MOZ_DIR" && ./mach build
+
+RUN cd "$MOZ_DIR" && ./mach resource-usage || echo "::warning::mach resource-usage failed; view above output for details"
+RUN sccache --show-stats || echo "::warning::sccache --show-stats failed; view above output for details"
 
 # Regenerate WPT certificates
 RUN cd "$MOZ_DIR/testing/web-platform/tests" && \
diff --git a/.github/workflows/firefox-macos.yml b/.github/workflows/firefox-macos.yml
--- a/.github/workflows/firefox-macos.yml
+++ b/.github/workflows/firefox-macos.yml
@@ -148,9 +148,16 @@ jobs:
           CI=false npm run build
           ./moz.build.sh
           cd ${{ env.MOZ_DIR }}
-          sccache --show-stats
+          if ! sccache --show-stats; then
+              echo "::warning::sccache is not working properly; view above output for details"
+          fi
           ./mach build
-          sccache --show-stats
+          if ! ./mach resource-usage; then
+              echo "::warning::mach resource-usage failed; view above output for details"
+          fi
+          if ! sccache --show-stats; then
+              echo "::warning::sccache is not working properly; view above output for details"
+          fi
 
       - name: Save build outputs
         uses: actions/cache/save@v4
